### ISSUE TITLE
can't install optifine

### ISSUE THREAD

**Issue by r4ffa47** [Mrmayman/quantum-launcher#5]
I was trying to install optifine by myself using the official OptiFine launcher, but it gives me a Java error whenever I try:
ava.io.FileNotFoundException: C:\Users\Utente\AppData\Roaming\QuantumLauncher\instances\hi\.minecraft\versions\1.21.3\1.21.3.json (Impossibile trovare il file specificato)
  at java.io.FileInputStream.open0(Native Method)
  at java.io.FileInputStream.open(Unknown Source)
  at java.io.FileInputStream.<init>(Unknown Source)
  at optifine.Utils.copyFile(Utils.java:217)
  at optifine.Installer.copyMinecraftVersion(Installer.java:521)
  at optifine.Installer.doInstall(Installer.java:95)
  at optifine.InstallerFrame.onInstall(InstallerFrame.java:425)
  at optifine.InstallerFrame.connEtoC1(InstallerFrame.java:490)
  at optifine.InstallerFrame.access$7(InstallerFrame.java:484)
  at optifine.InstallerFrame$IvjEventHandler.actionPerformed(InstallerFrame.java:46)
  at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
  at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
  at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
  at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
  at java.awt.Component.processMouseEvent(Unknown Source)
  at javax.swing.JComponent.processMouseEvent(Unknown Source)
  at java.awt.Component.processEvent(Unknown Source)
  at java.awt.Container.processEvent(Unknown Source)
  at java.awt.Component.dispatchEventImpl(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
  at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
  at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
  at java.awt.Container.dispatchEventImpl(Unknown Source)
  at java.awt.Window.dispatchEventImpl(Unknown Source)
  at java.awt.Component.dispatchEvent(Unknown Source)
  at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
  at java.awt.EventQueue.access$500(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.awt.EventQueue$3.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.awt.EventQueue$4.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue.dispatchEvent(Unknown Source)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.run(Unknown Source)

is this normal?

**Comment by Mrmayman** [comment]
I am working on a fix for this. Official OptiFine integration will come in QuantumLauncher v0.3 which may release in a few weeks

**Comment by Mrmayman** [comment]
OptiFine support has been added, please check the latest version of the launcher https://mrmayman.github.io/quantumlauncher

**Comment by Mrmayman** [comment]
Optifine installer is broken on windows, so i thought i'd reopen this
